





apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
data:
  JWT_SECRET_KEY: RjhCVlA5ZW9kSEw4blM3enhLOUhESzlpYmV6NUJya2lHbTdrWEJ3UEU1eGdqRml3cEp4eVFTZUx4bklwUGZZWVpHZXFSMVE1T1RCZ2R4UnFUOEtYOUE9PQo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      serviceAccountName: flask-backend-sa
      containers:
        - name: flask-backend
          image: tanishqjaiswal/flask-backend:v10
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/kube"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: backend
spec:
  selector:
    app: flask-backend
  ports:
    - port: 5000
      targetPort: 5000
      # nodePort: 30080   
  type: ClusterIP         
