









apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: platform
  labels:
    app: postgres
data:
  POSTGRES_DB: "<DB_NAME>"
  POSTGRES_USER: "<DB_USER>"
  POSTGRES_PASSWORD: "<DB_PASSWORD>"
  PGDATA: "/var/lib/postgresql/data/pgdata"


apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: platform
type: Opaque
data:
  <DB_PASSWORD>: cGFzc3dvcmQ= # base64 encoded <DB_PASSWORD>
  username: YWRtaW4=     # base64 encoded username
  database: am9ibWFuYWdlcg== # base64 encoded database name


apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: platform
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None




apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: platform
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: <POSTGRES_IMAGE>
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: <DB_PASSWORD>
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGDATA
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
                


